# Generated by Django 2.0.13 on 2019-05-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=500, unique=True)),
                ('short_url', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
